name: docusaurus-build

on:
  push:
    branches:
      - main # default branch name for each repo that docs should be push from
    paths:
      - docusaurus/**
jobs:
  build_docusaurus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build
        id: build
        run: |
            set -e  # if a command fails it stops the execution
            set -u  # script fails if trying to access to an undefined variable

            npm install -g https://github.com/GetStream/stream-chat-docusaurus-cli
            npx stream-chat-docusaurus -i -b

            DOCUSAURUS_BUILD_PATH=`npm list -g | head -1`/node_modules/stream-chat-docusaurus-cli/docusaurus/build/

            ls -la $DOCUSAURUS_BUILD_PATH

            echo "::set-output name=DOCUSAURUS_BUILD_PATH::$DOCUSAURUS_BUILD_PATH"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload APK
        run: aws s3 cp --recursive ${{ steps.build.outputs.DOCUSAURUS_BUILD_PATH }} s3://${{ secrets.AWS_S3_BUCKET }} --sse AES256

